version: '3.7'

services:
  graphql-api:
    container_name: graphqlApi
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - web
      - postgres
networks:
  web:
    external: true
  postgres:
    external: true
